Release v2
openinfradev/tks-mgmt-cluster-deploy pull request #12
Opened 2022-04-24 15:54 UTC by ktkfree

admin cluster 생성시 실패하는 부분에 대한 변경입니다. 전반적인 flow 를 모르는 상태에서의 수정이니 확인 부탁 드립니다.
 . keycloak 생성시 revision이 main 으로 고정되는 현상 변경.
 . tks-flow 에서 사용하는 tks-proto cm 생성

2022-04-24 22:32 UTC, Jaesang requested changes

2022-04-24 22:32 UTC, Jaesang commented on 05_install_decapod.sh
> +
tks-proto를 다운로드 받고 configmap으로 만들면 이게 어떤 역할을 하게되나요?

2022-04-24 22:32 UTC, Jaesang commented on 05_z1_install_keycloak.sh
> +argo submit --from wftmpl/install-admin-tools -p app_prefix=tks-admin -p revision=$TKS_RELEASE -n argo
`TKS_RELEASE` 변수에 대한 정의가 보이지 않습니다.

2022-04-25 01:05 UTC, zugwan commented on 05_z1_install_keycloak.sh
> +argo submit --from wftmpl/install-admin-tools -p app_prefix=tks-admin -p revision=$TKS_RELEASE -n argo
https://github.com/openinfradev/tks-mgmt-cluster-deploy/blob/main/conf.sh.example 사용자가 생성하는 설정 파일 내에 존재하게 됩니다.

2022-04-25 01:05 UTC, ktkfree commented on 05_z1_install_keycloak.sh
> +argo submit --from wftmpl/install-admin-tools -p app_prefix=tks-admin -p revision=$TKS_RELEASE -n argo
admin cluster 생성 스크립트 전반에 걸쳐 사용되는 global variable 로 알고있으며, conf.sh.example 에서 정의됩니다.

2022-04-25 01:05 UTC, zugwan approved these changes

2022-04-25 05:19 UTC, ktkfree commented
@Jaesang 님. 
request changes 확인 부탁 드립니다.

2022-04-26 03:32 UTC, Jaesang approved these changes

2022-04-26 03:32 UTC, merged