add keycloak install script
openinfradev/tks-mgmt-cluster-deploy pull request #29
Opened 2023-08-16 11:11 UTC by cho4036

keycloak 설치 스크립트 추가합니다.
keycloak 설치시, 크게 4가지 설정("none" or "self-signed" or "letsencrypt" or "exist-cert")이 가능하며
ingress tls 설정을 letsencrypt를 사용할 경우 cert-manager가 미리 설치 되어 있어야 합니다.

해당 과정을 수행하는 시점에서는 cluster api resource가 아직 bootstrap 노드에 있기 때문에 cert-manager가 admin cluster에 설치되지 않아 있습니다. 이로 인해 cert-manager를 설치하는 과정이 필요해 보여 추가하였습니다.

코멘트 부탁드립니다.

2023-08-18 07:41 UTC, zugwan commented
PR이 기반하고 있는 https://github.com/openinfradev/tks-mgmt-cluster-deploy/pull/28 내역이 업데이트 되었습니다. cert-manager 설치 시점이 말씀하신대로 문제가 있을 수 있어서 어드민 클러스터 설치 후에 바로 Cluster API 설치하는 내용으로 반영해 두었습니다. zugwan_wip 브랜치 기준으로 Rebase 후 다시 Push 부탁 드려요.

2023-08-25 04:55 UTC, zugwan requested changes

2023-08-25 04:55 UTC, zugwan commented on 05_z3_install_keycloak.sh
> +)
EOL 사용해서 변수 정의하는 이유가 있을까요?

문자열 그대로 정의해서 나오는 결과도 동일해서 문의를 드립니다.
```
$ KEYCLOAK_ANNOTATIONS=$(cat << EOL
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: tks-cluster-issuer
EOL
)
$ echo $KEYCLOAK_ANNOTATIONS
acme.cert-manager.io/http01-edit-in-place: "true" cert-manager.io/cluster-issuer: tks-cluster-issuer

$ KEYCLOAK_ANNOTATIONS_WITHOUT_EOL='acme.cert-manager.io/http01-edit-in-place: "true" cert-manager.io/cluster-issuer: tks-cluster-issuer'
$ echo $KEYCLOAK_ANNOTATIONS_WITHOUT_EOL
acme.cert-manager.io/http01-edit-in-place: "true" cert-manager.io/cluster-issuer: tks-cluster-issuer

$ diff <(echo $KEYCLOAK_ANNOTATIONS) <(echo $KEYCLOAK_ANNOTATIONS_WITHOUT_EOL)
$
```

2023-08-25 04:55 UTC, zugwan commented on templates/helm-keycloak.vo.template
> +postgresql:
https://github.com/openinfradev/tks-mgmt-cluster-deploy/blob/4f1b737ee6a90e30aa762dce50a077285f22201a/conf.sh.example#L26 과 같이 외부 DB 사용 여부를 설정 (비어 있다면 postgresql 인스턴스를 구축 과정에서 설치) 하는 부분이 있습니다. DB를 공유해서 사용하는 것을 기본으로 진행했으면 좋겠습니다.

2023-08-25 05:00 UTC, zugwan commented on 05_z3_install_keycloak.sh
> +)
자답 입니다 :)  쌍따옴표를 묶으면 개행 문자가 적용 되어서 멀티 라인 처리가 되는군요.
```
$ echo "$KEYCLOAK_ANNOTATIONS"
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: tks-cluster-issuer
```

2023-09-05 01:16 UTC, cho4036 commented
Keycloak 설치에 있어서 decapod 화 진행으로 결정 되었으므로 현 PR은 종료하겠습니다.

2023-09-05 01:16 UTC, closed without merging

2023-09-05 01:16 UTC, cho4036 commented on templates/helm-keycloak.vo.template
> +postgresql:
decapod 화 적용 시, 코멘트 내용 반영하겠습니다,

2023-09-05 01:18 UTC, ktkfree commented
몇 번 admin cluster 설치를 해보았는데, git_svc_toekn secret 의 username 필드가 설정한 정보로 업데이트 안되는 현상이 있었던것 같습니다. 시간 되실때 체크 한번 부탁 드립니다.

2023-09-05 05:33 UTC, zugwan commented
> 

decapod10으로 고정되는 문제 아니었나요? 해당 문제는 수정해서 zugwan_wip 브랜치에 반영되어 있습니다.